### ISSUE TITLE
Is a Question not bug

### ISSUE THREAD

**Issue by marketmix-matteoquintero** [pritishvaidya/react-native-flip-timer#1]
Hi, I want to know if it can be implemented with a countdown @pritishvaidya 👍

**Comment by pritishvaidya** [comment]
It has an in-built timer for now as you can provide the initial time in seconds. I've also exposed the card component to build a custom timer.

I would like to know more about what you would like to implement, perhaps with a simple demonstration or example.

Thanks

**Comment by marketmix-matteoquintero** [comment]
I would like to implement a countdown like this https://www.npmjs.com/package/react-native-countdown-component, but I like it more with the design and the animation that you did.

**Comment by pritishvaidya** [comment]
I'll have to make a separate package for it. The timer is not an issue but the cards animations are built in such a way that it flips and shows forward progression. For backward progression, the animations need to be reversed.

**Comment by marketmix-matteoquintero** [comment]
Of course it is the opposite that I need, I thank you very much, you will help me a lot with a project which I am working on.

**Comment by pritishvaidya** [comment]
I have published a new package for it 
- [GitHub](https://github.com/pritishvaidya/react-native-flip-countdown-timer)
- [npm](https://www.npmjs.com/package/react-native-flip-countdown-timer)

I didn't get much time to test it completely. Feel free to open the issue on that particular project.
