### ISSUE TITLE
Change default start value for prop time={}

### ISSUE THREAD

**Issue by Ros-ty** [pritishvaidya/react-native-flip-timer#13]
is it possible change default start value for property time after lock and unlock device?
for example: we have state seconds equal 50, and change state every second.

```
<Timer time={this.state.seconds} play={play} />
```

on mounting screen timer will start from 50 seconds. On locking device setState change value for state seconds. after 10 second and unlock devise state will equal 60, but timer will show 50 seconds.

**Comment by pritishvaidya** [comment]
If you provide a `number` that is different from the already changing value then it will restart the timer based on that number.
You can either change `time` in Timer Component or `number` in Custom Flip Card Component

https://github.com/pritishvaidya/react-native-flip-timer#properties

https://github.com/pritishvaidya/react-native-flip-timer/blob/39ab392f976e1ca3cc96ad490a94a8656d0571d6/src/components/flip-number/number-card.js#L37
