### ISSUE TITLE
wrapperStyle

### ISSUE THREAD

**Issue by marketmix-matteoquintero** [pritishvaidya/react-native-flip-timer#2]
Again it's me, please tell me if I'm well implemented **wrapperStyle** property because it looks like this, I want the **Timer** to have less width.

`<Timer wrapperStyle={{width:300}} time={0} play={this.state.play} />`

![whatsapp image 2019-03-05 at 4 29 24 pm](https://user-images.githubusercontent.com/47399551/53839060-92949000-3f64-11e9-8627-a198938e1f77.jpeg)

**Comment by pritishvaidya** [comment]
Can you add the code for it or a simple [snack](https://snack.expo.io/) link? I'll take a look.

**Comment by maartenvandillen** [comment]
I think you need to set the size of the flip number like this: `flipNumberProps={{ size: 50 }}`
